version: "3.8"

services:
  producer-1:
    build: ./producer
    container_name: producer-1
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - PRODUCER_ID=${PRODUCER_ID1}
      - FRAMES=${PRODUCER_FRAMES1}
      - AUDIO=${PRODUCER_AUDIO1}
      - DELAY=${DELAY1}
      - RATE=${RATE1}
    depends_on:
    - broker
    networks:
      public:
        ipv4_address: ${PRODUCER_IP1}

  producer-2:
    build: ./producer
    container_name: producer-2
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - PRODUCER_ID=${PRODUCER_ID2}
      - FRAMES=${PRODUCER_FRAMES2}
      - AUDIO=${PRODUCER_AUDIO2}
      - DELAY=${DELAY2}
      - RATE=${RATE2}
    depends_on:
    - broker
    networks:
      public:
        ipv4_address: ${PRODUCER_IP2}

  producer-3:
    build: ./producer
    container_name: producer-3
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - PRODUCER_ID=${PRODUCER_ID3}
      - FRAMES=${PRODUCER_FRAMES3}
      - AUDIO=${PRODUCER_AUDIO3}
      - DELAY=${DELAY3}
      - RATE=${RATE3}
    depends_on:
    - broker
    networks:
      public:
        ipv4_address: ${PRODUCER_IP3}

  broker:
    build: ./broker
    container_name: broker
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
    networks:
      public:
        ipv4_address: ${BROKER_IP}

  consumer-1:
    build: ./consumer
    container_name: consumer-1
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - CONSUMER_ADDRESS=${CONSUMER_IP1}:${CONSUMER_PORT}
    depends_on:
      - broker
    stdin_open: true
    tty: true
    networks:
      public:
        ipv4_address: ${CONSUMER_IP1}

  consumer-2:
    build: ./consumer
    container_name: consumer-2
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - CONSUMER_ADDRESS=${CONSUMER_IP2}:${CONSUMER_PORT}
    depends_on:
      - broker
    stdin_open: true
    tty: true
    networks:
      public:
        ipv4_address: ${CONSUMER_IP2}

  consumer-3:
    build: ./consumer
    container_name: consumer-3
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - CONSUMER_ADDRESS=${CONSUMER_IP3}:${CONSUMER_PORT}
    depends_on:
      - broker
    stdin_open: true
    tty: true
    networks:
      public:
        ipv4_address: ${CONSUMER_IP3}

networks:
  public:
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}