version: "3.8"

services:
  producer:
    build: ./producer
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - PRODUCER_ID=${PRODUCER_ID1}
      - STREAM1=${PRODUCER_STREAM1}
    depends_on:
    - broker
    networks:
      public:
        ipv4_address: ${PRODUCER_IP1}

  broker:
    build: ./broker
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
    networks:
      public:
        ipv4_address: ${BROKER_IP}

  consumer:
    build: ./consumer
    environment:
      - BROKER_ADDRESS=${BROKER_IP}:${BROKER_PORT}
      - CONSUMER_ADDRESS=${CONSUMER_IP1}:${CONSUMER_PORT}
    depends_on:
      - broker
    stdin_open: true
    tty: true
    networks:
      public:
        ipv4_address: ${CONSUMER_IP1}

networks:
  public:
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}